-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-10-20 17:18:58.745

-- tables
-- Table: EJERCICIO
CREATE TABLE EJERCICIO (
    id varchar(255) NOT NULL CONSTRAINT EJERCICIO_pk PRIMARY KEY,
    PATRON_id varchar(255) NOT NULL,
    CONSTRAINT EJERCICIO_PATRON FOREIGN KEY (PATRON_id)
    REFERENCES PATRON (id)
);

-- Table: EJERCICIO_PLANTILLA
CREATE TABLE EJERCICIO_PLANTILLA (
    EJERCICIO_id varchar(255) NOT NULL,
    PLANTILLA_id varchar(255) NOT NULL,
    CONSTRAINT EJERCICIO_PLANTILLA_pk PRIMARY KEY (EJERCICIO_id,PLANTILLA_id),
    CONSTRAINT EJERCICIO_PLANTILLA_EJERCICIO FOREIGN KEY (EJERCICIO_id)
    REFERENCES EJERCICIO (id),
    CONSTRAINT EJERCICIO_PLANTILLA_PLANTILLA FOREIGN KEY (PLANTILLA_id)
    REFERENCES PLANTILLA (id)
);

-- Table: EJERCICIO_REALIZADO
CREATE TABLE EJERCICIO_REALIZADO (
    SESION_GYM_fecha date NOT NULL,
    EJERCICIO_id varchar(255) NOT NULL,
    CONSTRAINT EJERCICIO_REALIZADO_pk PRIMARY KEY (SESION_GYM_fecha,EJERCICIO_id),
    CONSTRAINT EJERCICIO_REALIZADO_SESION_GYM FOREIGN KEY (SESION_GYM_fecha)
    REFERENCES SESION_GYM (fecha),
    CONSTRAINT EJERCICIO_REALIZADO_EJERCICIO FOREIGN KEY (EJERCICIO_id)
    REFERENCES EJERCICIO (id)
);

-- Table: ETAPA
CREATE TABLE ETAPA (
    id varchar(255) NOT NULL CONSTRAINT ETAPA_pk PRIMARY KEY,
    fehca_ini date NOT NULL,
    fecha_fin date NOT NULL
);

-- Table: PATRON
CREATE TABLE PATRON (
    id varchar(255) NOT NULL CONSTRAINT PATRON_pk PRIMARY KEY
);

-- Table: PLANTILLA
CREATE TABLE PLANTILLA (
    id varchar(255) NOT NULL CONSTRAINT PLANTILLA_pk PRIMARY KEY
);

-- Table: SERIE_PLANTILLA
CREATE TABLE SERIE_PLANTILLA (
    id varchar(255) NOT NULL CONSTRAINT SERIE_PLANTILLA_pk PRIMARY KEY,
    repeticiones integer NOT NULL,
    rir integer NOT NULL,
    EJERCICIO_PLANTILLA_EJERCICIO_id varchar(255) NOT NULL,
    EJERCICIO_PLANTILLA_PLANTILLA_id varchar(255) NOT NULL,
    CONSTRAINT SERIE_PLANTILLA_EJERCICIO_PLANTILLA FOREIGN KEY (EJERCICIO_PLANTILLA_EJERCICIO_id,EJERCICIO_PLANTILLA_PLANTILLA_id)
    REFERENCES EJERCICIO_PLANTILLA (EJERCICIO_id,PLANTILLA_id)
);

-- Table: SERIE_REALIZADA
CREATE TABLE SERIE_REALIZADA (
    id varchar(255) NOT NULL CONSTRAINT SERIE_REALIZADA_pk PRIMARY KEY,
    peso integer NOT NULL,
    repeticiones integer NOT NULL,
    rir integer NOT NULL,
    EJERCICIO_REALIZADO_SESION_GYM_fecha date NOT NULL,
    EJERCICIO_REALIZADO_EJERCICIO_id varchar(255) NOT NULL,
    CONSTRAINT SERIE_REALIZADA_EJERCICIO_REALIZADO FOREIGN KEY (EJERCICIO_REALIZADO_SESION_GYM_fecha,EJERCICIO_REALIZADO_EJERCICIO_id)
    REFERENCES EJERCICIO_REALIZADO (SESION_GYM_fecha,EJERCICIO_id)
);

-- Table: SESION_GYM
CREATE TABLE SESION_GYM (
    fecha date NOT NULL CONSTRAINT SESION_GYM_pk PRIMARY KEY,
    ETAPA_id varchar(255) NOT NULL,
    PLANTILLA_id varchar(255),
    CONSTRAINT SESION_GYM_ETAPA FOREIGN KEY (ETAPA_id)
    REFERENCES ETAPA (id),
    CONSTRAINT SESION_GYM_PLANTILLA FOREIGN KEY (PLANTILLA_id)
    REFERENCES PLANTILLA (id)
);

-- End of file.

