-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-10-20 17:18:58.745

-- foreign keys
-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- ALTER TABLE DROP CONSTRAINT not supported

-- tables
DROP TABLE EJERCICIO;

DROP TABLE EJERCICIO_PLANTILLA;

DROP TABLE EJERCICIO_REALIZADO;

DROP TABLE ETAPA;

DROP TABLE PATRON;

DROP TABLE PLANTILLA;

DROP TABLE SERIE_PLANTILLA;

DROP TABLE SERIE_REALIZADA;

DROP TABLE SESION_GYM;

-- End of file.

