-- INSERT EJERCICIO;
INSERT INTO EJERCICIO (id,PATRON_id)
VALUES
    ("pb",	"push"),
    ("pm",	"push");

-- INSERT PATRON;
INSERT INTO PATRON (id)
VALUES
    ("push"),
    ("pull"),
    ("leg");


-- DROP TABLE EJERCICIO_PLANTILLA;

-- DROP TABLE EJERCICIO_REALIZADO;

-- DROP TABLE ETAPA;


-- DROP TABLE PLANTILLA;

-- DROP TABLE SERIE_PLANTILLA;

-- DROP TABLE SERIE_REALIZADA;

-- DROP TABLE SESION_GYM;